//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unach.Equipo1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int IDCliente { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string NumeroTelefono { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<int> TipoClienteID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
    
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
