//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unach.Equipo1.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int IDTransaccion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<int> ProductoID { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
